[package]
name = "datafusion_jni"
version = "0.16.0"
homepage = "https://github.com/apache/datafusion"
repository = "https://github.com/apache/datafusion"
authors = ["Apache Arrow <dev@arrow.apache.org>"]
description = "Build and run queries against data"
readme = "README.md"
license = "Apache-2.0"
edition = "2021"

[dependencies]
jni = "^0.21.0"
tokio = "^1.43.0"
arrow = { version = "^54.2.0", features = ["ffi", "ipc_compression"] }
datafusion = "^45.0.0"
futures = "0.3.31"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
strip = true
